language: ruby
rvm:
  - 2.1.1
cache:
  - bundler
  - apt
notifications:
  hipchat: 83906daf46b0ce558ce21f13353861@246078
  on_success: always
  on_failure: always
script:
  - bundle exec rspec
addons:
  code_climate:
    repo_token: 08d4f3eddf4ae14785eeb099a4efaf67cb5009aa41316f035843c0a1579f343f
